const express=require('express')
const connectdb = require('./connectdb')
const router = require('./routes')
require('dotenv').config()
const app=express()
const port=process.env.port
app.use(express.json())
connectdb()
app.use('/',router)
app.listen(port,console.log("server is running at port: "+port))